CREATE TABLE [etl].[ODFBActivity] (
    [Username]                     NVARCHAR (255)  NULL,
    [Branch]                       NVARCHAR (255)  NULL,
    [Department]                   NVARCHAR (255)  NULL,
    [Office]                       NVARCHAR (255)  NULL,
    [Section]                      NVARCHAR (255)  NULL,
    [IsActive]                     BIT             NOT NULL,
    [IsEmployee]                   INT             NULL,
    [NotUsingOneDrive]             INT             NULL,
    [NotUsingOneDriveText]         NVARCHAR (255)  NULL,
    [ODB_CollaboratedByOthers]     INT             NULL,
    [ODB_CollaboratedByOwner]      INT             NULL,
    [ODB_TotalFileSharedEXT]       BIGINT          NULL,
    [ODB_TotalFileSharedINT]       BIGINT          NULL,
    [ODB_TotalFileSynched]         BIGINT          NULL,
    [ODB_TotalFileViewed_Modified] BIGINT          NULL,
    [ODB_TotalofAllActivities]     BIGINT          NULL,
    [ProfileId]                    FLOAT (53)      NULL,
    [ProfilePicture]               BIT             NOT NULL,
    [Storage_Allocated]            DECIMAL (38, 6) NULL,
    [Storage_used]                 DECIMAL (38, 6) NULL,
    [Storage_used_perct]           DECIMAL (38, 6) NULL,
    [TotalFiles]                   BIGINT          NULL,
    [Unit]                         NVARCHAR (255)  NULL,
    [UsersSharing]                 INT             NULL,
    [UsersSharingText]             NVARCHAR (255)  NULL,
    [UsersSyncing]                 INT             NULL,
    [UsersSyncingText]             NVARCHAR (255)  NULL,
    [UsingOneDrive]                INT             NULL,
    [UsingOneDriveText]            NVARCHAR (255)  NULL
);

