CREATE TABLE [dbo].[AnalyticsO365Groups] (
    [ID]                      INT             IDENTITY (1, 1) NOT NULL,
    [GroupId]                 NVARCHAR (255)  NULL,
    [GroupName]               NVARCHAR (255)  NULL,
    [MailAddress]             NVARCHAR (255)  NULL,
    [MailEnabled]             BIT             NULL,
    [AllowExternalSenders]    BIT             NULL,
    [AutoSubscribeNewMembers] BIT             NULL,
    [Site]                    NVARCHAR (255)  NULL,
    [PublicPrivate]           NVARCHAR (50)   NULL,
    [EPAWide]                 BIT             NULL,
    [Office]                  NVARCHAR (255)  NULL,
    [CreatedDate]             DATETIME        NULL,
    [CreatedDateMonth]        INT             NULL,
    [CreatedDateYear]         INT             NULL,
    [Storage_GB]              DECIMAL (18, 6) NULL,
    [Storage_Used_Perct]      DECIMAL (18, 4) NULL,
    [Storage_Quota_GB]        DECIMAL (18, 6) NULL,
	[PrimaryOwner] VARCHAR(255) NULL,
	[Owners] VARCHAR(MAX) NULL,
	[TeamDisplayName] VARCHAR(255) NULL,
	[TeamDescription] VARCHAR(MAX) NULL,
	[TeamInternalId] VARCHAR(255) NULL,
	[TeamClassification] VARCHAR(255) NULL,
	[TeamSpecialization] VARCHAR(255) NULL,
	[TeamVisibility] VARCHAR(255) NULL,
	[TeamDiscoverySettings] VARCHAR(255) NULL,
	[TeamResponseHeaders] VARCHAR(MAX) NULL,
	[TeamStatusCode] VARCHAR(255) NULL,
	[TeamIsArchived] BIT NOT NULL DEFAULT 0,
	[TeamWebUrl] VARCHAR(255) NULL,
	[ReportPeriod] VARCHAR(255) NULL,
	[ReportRefreshDate] DATETIME NULL,
	[IsDeleted] BIT NOT NULL DEFAULT 0,
	[LastActivityDate] DATETIME NULL,
	[MemberCount] BIGINT NULL,
	[ExchangeReceivedEmailCount] BIGINT NULL,
	[SharePointActiveFileCount] BIGINT NULL,
	[ExchangeMailboxTotalItemCount] BIGINT NULL,
	[ExchangeMailboxStorageUsed_Byte] BIGINT NULL,
	[SharePointTotalFileCount] BIGINT NULL,
	[SharePointSiteStorageUsed_Byte] BIGINT NULL,
	[IsSiteProvisioned] BIT NOT NULL DEFAULT 0,
    [DTADDED]                 DATETIME        CONSTRAINT [DF_EPA-Analytics-O365Groups_DTADDED] DEFAULT (getdate()) NOT NULL,
    [DTUPD]                   DATETIME        NULL,
    CONSTRAINT [PK_EPA-Analytics-O365Groups] PRIMARY KEY CLUSTERED ([ID] ASC)
);

