CREATE TABLE [dbo].[GraphSkypeForBusinessActivityUserDetail] (
    [UPN]                                             NVARCHAR (128) NOT NULL,
    [LastActivityDate]                                DATETIME       NOT NULL,
    [Deleted]                                         NVARCHAR (MAX) NULL,
    [DeletedDate]                                     DATETIME       NULL,
    [TotalPeerToPeerSessionCount]                     BIGINT         NULL,
    [TotalOrganizedConferenceCount]                   BIGINT         NULL,
    [TotalParticipatedConferenceCount]                BIGINT         NULL,
    [PeerToPeerLastActivityDate]                      DATETIME       NULL,
    [OrganizedConferenceLastActivityDate]             DATETIME       NULL,
    [ParticipatedConferenceLastActivityDate]          DATETIME       NULL,
    [PeerToPeerIMCount]                               BIGINT         NULL,
    [PeerToPeerAudioCount]                            BIGINT         NULL,
    [PeerToPeerAudioMinutes]                          BIGINT         NULL,
    [PeerToPeerVideoCount]                            BIGINT         NULL,
    [PeerToPeerVideoMinutes]                          BIGINT         NULL,
    [PeerToPeerAppSharingCount]                       BIGINT         NULL,
    [PeerToPeerFileTransferCount]                     BIGINT         NULL,
    [OrganizedConferenceIMCount]                      BIGINT         NULL,
    [OrganizedConferenceAudioVideoCount]              BIGINT         NULL,
    [OrganizedConferenceAudioVideoMinutes]            BIGINT         NULL,
    [OrganizedConferenceAppSharingCount]              BIGINT         NULL,
    [OrganizedConferenceWebCount]                     BIGINT         NULL,
    [OrganizedConferenceDialInOut3rdPartyCount]       BIGINT         NULL,
    [OrganizedConferenceCloudDialInOutMicrosoftCount] BIGINT         NULL,
    [OrganizedConferenceCloudDialInMicrosoftMinutes]  BIGINT         NULL,
    [OrganizedConferenceCloudDialOutMicrosoftMinutes] BIGINT         NULL,
    [ParticipatedConferenceIMCount]                   BIGINT         NULL,
    [ParticipatedConferenceAudioVideoCount]           BIGINT         NULL,
    [ParticipatedConferenceAudioVideoMinutes]         BIGINT         NULL,
    [ParticipatedConferenceAppSharingCount]           BIGINT         NULL,
    [ParticipatedConferenceWebCount]                  BIGINT         NULL,
    [ParticipatedConferenceDialInOut3rdPartyCount]    BIGINT         NULL,
    [ProductsAssigned]                                NVARCHAR (MAX) NULL,
    [ReportRefreshDate]                               DATETIME       NOT NULL,
    [ReportPeriod]                                    INT            NOT NULL,
    CONSTRAINT [PK_dbo.SkypeForBusinessActivityUserDetail] PRIMARY KEY CLUSTERED ([UPN] ASC, [LastActivityDate] ASC)
);

