CREATE TABLE [dbo].[O365PreviewSkypeMonthlyRollup] (
    [ReportingDateID]                             INT          NOT NULL,
    [Office]                                      VARCHAR (50) NOT NULL,
    [TotalUsers]                                  INT          NULL,
    [TotalActiveUsers]                            INT          NULL,
    [TotalEmployeeUsers]                          INT          NULL,
    [TotalContractorUsers]                        INT          NULL,
    [UsingPeerToPeerCount]                        INT          NULL,
    [UsingPeerToPeerEnabledCount]                 INT          NULL,
    [UsingPeerToPeerEmployeeCount]                INT          NULL,
    [UsingPeerToPeerContractorCount]              INT          NULL,
    [UsingOrganizedCount]                         INT          NULL,
    [UsingOrganizedEnabledCount]                  INT          NULL,
    [UsingOrganizedEmployeeCount]                 INT          NULL,
    [UsingOrganizedContractorCount]               INT          NULL,
    [UsingParticipatedCount]                      INT          NULL,
    [UsingParticipatedEnabledCount]               INT          NULL,
    [UsingParticipatedEmployeeCount]              INT          NULL,
    [UsingParticipatedContractorCount]            INT          NULL,
    [TotalAvgActiveDays]                          INT          NULL,
    [TotalofAllActivities]                        INT          NULL,
    [TotalPeerToPeerSessionCount]                 INT          NULL,
    [TotalOrganizedConferenceCount]               INT          NULL,
    [TotalParticipatedConferenceCount]            INT          NULL,
    [PeerToPeerAudioMinutes]                      INT          NULL,
    [PeerToPeerVideoMinutes]                      INT          NULL,
    [PeerToPeerIMCount]                           INT          NULL,
    [OrganizedAudioMinutes]                       INT          NULL,
    [OrganizedIMCount]                            INT          NULL,
    [OrganizedAudioCount]                         INT          NULL,
    [ParticipatedAudioMinutes]                    INT          NULL,
    [ParticipatedIMCount]                         INT          NULL,
    [ParticipatedAudioCount]                      INT          NULL,
    [DTADDED]                                     DATETIME     NULL,
    [DTUPD]                                       DATETIME     NULL,
    [UsingOrganizedOrParticipatedCount]           INT          NULL,
    [UsingOrganizedOrParticipatedEnabledCount]    INT          NULL,
    [UsingOrganizedOrParticipatedEmployeeCount]   INT          NULL,
    [UsingOrganizedOrParticipatedContractorCount] INT          NULL,
    CONSTRAINT [PK_O365PreviewSkypeMonthlyRollup] PRIMARY KEY CLUSTERED ([ReportingDateID] ASC, [Office] ASC)
);

