CREATE TABLE [dbo].[TenantWebAddIn] (
    [ID]               INT              IDENTITY (1, 1) NOT NULL,
    [tenantSiteId]     INT              NULL,
    [tenantWebId]      INT              NULL,
    [SiteGuid]         UNIQUEIDENTIFIER NULL,
    [WebGuid]          UNIQUEIDENTIFIER NOT NULL,
    [AppGuid]          UNIQUEIDENTIFIER NOT NULL,
    [AppTitle]         VARCHAR (255)    NULL,
    [AppDescription]   VARCHAR (2055)   NULL,
    [AppPermissions]   VARCHAR (2055)   NULL,
    [AppStatus]        VARCHAR (75)     NULL,
    [HostedType]       VARCHAR (75)     NULL,
    [HostWebUrl]       VARCHAR (255)    NULL,
    [AppRedirectUrl]   VARCHAR (255)    NULL,
    [AppPrincipalId]   VARCHAR (255)    NULL,
    [AppWebFullUrl]    VARCHAR (255)    NULL,
    [ImageFallbackUrl] VARCHAR (255)    NULL,
    [ImageUrl]         VARCHAR (255)    NULL,
    [InError]          BIT              CONSTRAINT [DF_TenantWebAddIn_InError] DEFAULT ((0)) NOT NULL,
    [ProductGuid]      UNIQUEIDENTIFIER NULL,
    [RemoteAppUrl]     VARCHAR (255)    NULL,
    [SettingsPageUrl]  VARCHAR (255)    NULL,
    [StartPage]        VARCHAR (255)    NULL,
    [EulaUrl]          VARCHAR (255)    NULL,
    [PrivacyUrl]       VARCHAR (255)    NULL,
    [Publisher]        VARCHAR (255)    NULL,
    [SupportUrl]       VARCHAR (255)    NULL,
    CONSTRAINT [PK_TenantWebAddIn] PRIMARY KEY CLUSTERED ([ID] ASC)
);

