name: Angular Build
on:
  push:
    branches:
      - main
    

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Angular

    steps:
      - uses: actions/checkout@v3

      - name: Create Angular Artificats Directory
        run: mkdir AngularArtifacts

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: npm build
        run: npm run build -- --prod

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AngularArtifacts
          path: ./dist